### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3793: ordinal not in range(128)

### ISSUE THREAD

**Issue by likerainsun** [dhlee347/pytorchic-bert#13]
I downloaded the pretrained bert model.
Running the fine-tuning step brings an error
when loading vocab file, I assume.

Any idea to fix it?

![image](https://user-images.githubusercontent.com/11925315/59081623-09597480-892a-11e9-9305-3ccc87ef3158.png)

**Comment by dhlee347** [comment]
The tokenization.py is from the google bert official repo. How about reporting this bug to the repo? (you might be able to reproduce the same error in that codes.)
