### ISSUE TITLE
Can you please provide books_large_all.txt? And also, the pretrained model uncased_L-12_H-768_A-12/bert_model.ckpt? 

### ISSUE THREAD

**Issue by AyanKumarBhunia** [dhlee347/pytorchic-bert#18]

**Comment by dhlee347** [comment]
You can download uncased_L-12_H-768_A-12/bert_model.ckpt from https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip in https://github.com/google-research/bert
