### ISSUE TITLE
Running SQUAD

### ISSUE THREAD

**Issue by ismaeel123** [dhlee347/pytorchic-bert#28]
Can i fune tune this model to make it run squad?

**Comment by dhlee347** [comment]
basically yes, but you have to make squad finetuning codes with base bert model.

**Comment by mineshmathew** [comment]
@dhlee347 
Will you be adding code for fine tuning for SQuAD?
Do you know any repo (pytorch one ) where I can see how this is done
I am a bit confused about how the output layer is set up in case of fine tuning BERT for question answering


Thanks in advance

**Comment by dhlee347** [comment]
You can use huggingface/transformers for applying transformers to a variety of NLP tasks
