### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by thomwolf** [dhlee347/pytorchic-bert#4]
I like it! You may want to check the work NVIDIA did to incorporate FP16 training in [our repo](https://github.com/huggingface/pytorch-pretrained-BERT/pull/116). It really speeds the model on recent GPUs (4x speed up on a V100!).
You basically just have to change the Layer Norm module in the model and tweak a bit the training to use NVIDIA's apex.

**Comment by dhlee347** [comment]
Thanks, wolf ! Your team's works (Open AI GPT + Google BERT in Pytorch) always helped my research a lot ! I also consider to add the FP16 feature with NVIDIA's apex.

**Comment by abhishekvermasg** [comment]
have you implemented the FP16 tweak in your code?

**Comment by dhlee347** [comment]
Sorry, I don't have enough time to do it recently. I'll do it when I have a time maybe next year. Thanks !
