### ISSUE TITLE
Question About fine-tuning

### ISSUE THREAD

**Issue by graykode** [dhlee347/pytorchic-bert#9]
https://github.com/dhlee347/pytorchic-bert/blob/master/classify.py#L137
When fine-tuning, is there no needed '[SEP]', '[CLS]'?
In google-research code, They add 'CLS' and 'SEP' in fine-tuning.
https://github.com/santhoshkolloju/Abstractive-Summarization-With-Transfer-Learning/blob/master/preprocess.py#L197

**Comment by dhlee347** [comment]
Sorry for the late response, 
 '[SEP]', '[CLS]' are added at https://github.com/dhlee347/pytorchic-bert/blob/master/classify.py#L119
